### ISSUE TITLE
使用ci的时候点击git仓库出现404project not found

### ISSUE THREAD

**Issue by a1418692409** [go-to-cloud/go-to-cloud#10]
![图片](https://github.com/go-to-cloud/go-to-cloud/assets/20787453/094e925c-9057-439b-8bcd-0358fb049587)

**Comment by a1418692409** [comment]
这个git项目地址单独是可以打开的

**Comment by fanhousanbu** [comment]
如果你使用的是gitlab作为代码仓库，那这个错误很可能是token权限不足或者过期，参考：https://gitlab.com/gitlab-org/gitlab-foss/-/issues/29022；

类似的，github如果在权限不足时返回的也是404错误
